#!/usr/bin/python3

def raise_exception():
    num = 3
    name = "TM"
    results = num + name
